### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by NikunjKhangwal** [vamsi3/screen-translator#21]
FATAL EXCEPTION: main
Process: com.vamsi3.android.screentranslator, PID: 23857
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.vamsi3.android.screentranslator/.feature.translate.ScreenTranslatorAccessibilityService }: app is in background uid UidRecord{58a45e9 u0a5624 CEM  idle change:cached procs:0 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1872)
	at android.app.ContextImpl.startService(ContextImpl.java:1828)
	at android.content.ContextWrapper.startService(ContextWrapper.java:786)
	at com.vamsi3.android.screentranslator.feature.translate.ScreenTranslatorTileService.onClick(Unknown Source:64)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:452)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by Johnnyhoes55** [comment]
v0.0.3 works fine

**Comment by NikunjK8** [comment]
0.0.3 is also crashing for me
